modLoader="javafml"
loaderVersion="[40,)"
license="GPL 3.0 for the rest, CC BY-NC-SA 3.0 for QuarkSortingHandler.java"

[[mods]]
modId="inventorysorter"
version="${file.jarVersion}"
displayName="Simple Inventory Sorter (Configurable)"
displayURL="https://github.com/qyurila/inventorysorter"
credits="Vazkii (Quark sort order)"
authors="cpw (original mod), QriLa (fork)"
description='''
Simple inventory sorting, in configurable order.

Forked from the original by cpw.
This fork is meant to be a DROP-IN REPLACEMENT for the original mod. DELETE the original mod first!

You can finally customize the sort order, while maintaining the compatibility of the original mod!
The default sort order is the same as Quark's Inventory Sorting feature.
You can change the order to raw item ID, creative tab, name, etc. in the config file (or using the "Configured" mod). No relaunch required.

Middle-click to sort your inventory.
'''
